// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ gpu_top__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__glbl_rst_n;
        CData/*0:0*/ gpu_top__DOT__reset_sync_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__reset_sync_inst__DOT__arst_n;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__shader_loader_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__core0__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__core0__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__vf_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__vf_inst__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__rast_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__rast_inst__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__frag_fifo__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__frag_fifo__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__fs_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__fs_inst__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__tex_unit__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__tex_unit__DOT__rst_n;
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(i_bus_we,0,0);
        CData/*0:0*/ gpu_top__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__i_bus_we;
        CData/*2:0*/ gpu_top__DOT__pipe_state;
        CData/*2:0*/ gpu_top__DOT__next_pipe_state;
        CData/*0:0*/ gpu_top__DOT__pipeline_start;
        CData/*0:0*/ gpu_top__DOT__pipeline_busy;
        CData/*0:0*/ gpu_top__DOT__vertex_fetch_done;
        CData/*0:0*/ gpu_top__DOT__rasterizer_done;
        CData/*0:0*/ gpu_top__DOT__shader_exec_done;
        CData/*0:0*/ gpu_top__DOT__controller_start;
        CData/*0:0*/ gpu_top__DOT__controller_irq;
        CData/*2:0*/ gpu_top__DOT__master_req;
        CData/*0:0*/ gpu_top__DOT__slave_req;
        CData/*0:0*/ gpu_top__DOT__shader_exec_en;
        CData/*4:0*/ gpu_top__DOT__shader_opcode;
        CData/*3:0*/ gpu_top__DOT__shader_rd;
        CData/*3:0*/ gpu_top__DOT__shader_rs1;
        CData/*3:0*/ gpu_top__DOT__shader_rs2;
        CData/*0:0*/ gpu_top__DOT__rast_start;
        CData/*0:0*/ gpu_top__DOT__rast_frag_valid;
        CData/*0:0*/ gpu_top__DOT__fifo_wr;
        CData/*0:0*/ gpu_top__DOT__fifo_rd;
        CData/*0:0*/ gpu_top__DOT__fifo_full;
        CData/*0:0*/ gpu_top__DOT__fifo_empty;
        CData/*0:0*/ gpu_top__DOT__fs_in_valid;
        CData/*0:0*/ gpu_top__DOT__tex_req_valid;
        CData/*0:0*/ gpu_top__DOT__texel_valid;
        CData/*0:0*/ gpu_top__DOT__pixel_we;
        CData/*0:0*/ gpu_top__DOT__reset_sync_inst__DOT__srst_n;
        CData/*0:0*/ gpu_top__DOT__reset_sync_inst__DOT__rst_s1;
        CData/*0:0*/ gpu_top__DOT__reset_sync_inst__DOT__rst_s2;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__i_bus_we;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__i_pipeline_busy;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__o_start_pipeline;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__o_irq;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__start_cmd;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__irq_clear_cmd;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__irq_pending;
    };
    struct {
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__busy_last_cycle;
        CData/*0:0*/ gpu_top__DOT__ctrl_inst__DOT__fire_start_pulse;
        CData/*3:0*/ gpu_top__DOT__ctrl_inst__DOT__pending_starts_count;
        CData/*0:0*/ gpu_top__DOT__shader_loader_inst__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__shader_loader_inst__DOT__i_host_we;
        CData/*7:0*/ gpu_top__DOT__shader_loader_inst__DOT__i_host_addr;
        CData/*7:0*/ gpu_top__DOT__shader_loader_inst__DOT__i_gpu_addr;
        CData/*4:0*/ gpu_top__DOT__decoder_inst__DOT__o_opcode;
        CData/*3:0*/ gpu_top__DOT__decoder_inst__DOT__o_rd_addr;
        CData/*3:0*/ gpu_top__DOT__decoder_inst__DOT__o_rs1_addr;
        CData/*3:0*/ gpu_top__DOT__decoder_inst__DOT__o_rs2_addr;
        CData/*0:0*/ gpu_top__DOT__core0__DOT__i_exec_en;
        CData/*4:0*/ gpu_top__DOT__core0__DOT__i_opcode;
        CData/*3:0*/ gpu_top__DOT__core0__DOT__i_rd_addr;
        CData/*3:0*/ gpu_top__DOT__core0__DOT__i_rs1_addr;
        CData/*3:0*/ gpu_top__DOT__core0__DOT__i_rs2_addr;
        CData/*0:0*/ gpu_top__DOT__core0__DOT__o_mem_req;
        CData/*0:0*/ gpu_top__DOT__core0__DOT__i_mem_ready;
        CData/*0:0*/ gpu_top__DOT__core0__DOT__reg_write_en;
        CData/*0:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_wr_en;
        CData/*3:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_wr_addr;
        CData/*3:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_rd_addr_a;
        CData/*3:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_rd_addr_b;
        CData/*4:0*/ gpu_top__DOT__core0__DOT__alu_inst__DOT__i_opcode;
        CData/*0:0*/ gpu_top__DOT__interconnect_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__interconnect_inst__DOT__rst_n;
        CData/*2:0*/ gpu_top__DOT__interconnect_inst__DOT__i_master_req;
        CData/*0:0*/ gpu_top__DOT__interconnect_inst__DOT__o_slave_req;
        CData/*2:0*/ gpu_top__DOT__interconnect_inst__DOT__grants;
        CData/*1:0*/ gpu_top__DOT__interconnect_inst__DOT__granted_index;
        CData/*1:0*/ gpu_top__DOT__interconnect_inst__DOT__slave_select;
        CData/*0:0*/ gpu_top__DOT__interconnect_inst__DOT____Vlvbound_h40f0798e__0;
        CData/*2:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__i_requests;
        CData/*2:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__o_grants;
        CData/*2:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__last_grant_reg;
        CData/*2:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__next_grant_state;
        CData/*5:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__priority_mask;
        CData/*5:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__masked_requests;
        CData/*0:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__unnamedblk1__DOT__grant_found;
        CData/*0:0*/ gpu_top__DOT__vf_inst__DOT__i_start_fetch;
        CData/*0:0*/ gpu_top__DOT__vf_inst__DOT__o_fetch_done;
        CData/*0:0*/ gpu_top__DOT__vf_inst__DOT__o_mem_req;
        CData/*0:0*/ gpu_top__DOT__vf_inst__DOT__i_mem_ready;
        CData/*1:0*/ gpu_top__DOT__vf_inst__DOT__current_state;
        CData/*1:0*/ gpu_top__DOT__vf_inst__DOT__next_state;
        CData/*0:0*/ gpu_top__DOT__rast_inst__DOT__i_start;
        CData/*0:0*/ gpu_top__DOT__rast_inst__DOT__o_fragment_valid;
        CData/*0:0*/ gpu_top__DOT__rast_inst__DOT__o_done;
        CData/*0:0*/ gpu_top__DOT__rast_inst__DOT__is_running;
        CData/*0:0*/ gpu_top__DOT__rast_inst__DOT__is_inside;
        CData/*0:0*/ gpu_top__DOT__frag_fifo__DOT__i_wr_en;
        CData/*0:0*/ gpu_top__DOT__frag_fifo__DOT__i_rd_en;
        CData/*0:0*/ gpu_top__DOT__frag_fifo__DOT__o_full;
        CData/*0:0*/ gpu_top__DOT__frag_fifo__DOT__o_empty;
        CData/*5:0*/ gpu_top__DOT__frag_fifo__DOT__wr_ptr_reg;
        CData/*5:0*/ gpu_top__DOT__frag_fifo__DOT__rd_ptr_reg;
        CData/*5:0*/ gpu_top__DOT__frag_fifo__DOT__wr_ptr_next;
        CData/*5:0*/ gpu_top__DOT__frag_fifo__DOT__rd_ptr_next;
        CData/*6:0*/ gpu_top__DOT__frag_fifo__DOT__count_reg;
        CData/*6:0*/ gpu_top__DOT__frag_fifo__DOT__count_next;
        CData/*0:0*/ gpu_top__DOT__fs_inst__DOT__i_frag_valid;
        CData/*0:0*/ gpu_top__DOT__fs_inst__DOT__o_tex_req_valid;
        CData/*0:0*/ gpu_top__DOT__fs_inst__DOT__i_texel_valid;
        CData/*0:0*/ gpu_top__DOT__fs_inst__DOT__o_pixel_valid;
    };
    struct {
        CData/*0:0*/ gpu_top__DOT__fs_inst__DOT__tex_request_sent;
        CData/*4:0*/ gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__i_opcode;
        CData/*0:0*/ gpu_top__DOT__tex_unit__DOT__i_req_valid;
        CData/*0:0*/ gpu_top__DOT__tex_unit__DOT__o_data_valid;
        CData/*7:0*/ gpu_top__DOT__tex_unit__DOT__tex_x;
        CData/*7:0*/ gpu_top__DOT__tex_unit__DOT__tex_y;
        CData/*0:0*/ gpu_top__DOT__fb_inst__DOT__clk;
        CData/*0:0*/ gpu_top__DOT__fb_inst__DOT__rst_n;
        CData/*0:0*/ gpu_top__DOT__fb_inst__DOT__i_pixel_we;
        CData/*0:0*/ gpu_top__DOT__fb_inst__DOT__o_mem_req;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__glbl_rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__reset_sync_inst__DOT__arst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__reset_sync_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__ctrl_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__ctrl_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__shader_loader_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__core0__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__core0__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__core0__DOT__reg_file_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__core0__DOT__reg_file_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__vf_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__vf_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__rast_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__rast_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__frag_fifo__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__frag_fifo__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__fs_inst__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__fs_inst__DOT__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__tex_unit__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__gpu_top__DOT__tex_unit__DOT__rst_n__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ gpu_top__DOT__vertex_count;
        SData/*15:0*/ gpu_top__DOT__current_vertex;
        SData/*11:0*/ gpu_top__DOT__shader_imm;
        SData/*9:0*/ gpu_top__DOT__v0x;
        SData/*9:0*/ gpu_top__DOT__v0y;
        SData/*9:0*/ gpu_top__DOT__v1x;
        SData/*9:0*/ gpu_top__DOT__v1y;
        SData/*9:0*/ gpu_top__DOT__v2x;
        SData/*9:0*/ gpu_top__DOT__v2y;
        SData/*9:0*/ gpu_top__DOT__frag_x;
        SData/*9:0*/ gpu_top__DOT__frag_y;
        SData/*9:0*/ gpu_top__DOT__fs_in_x;
        SData/*9:0*/ gpu_top__DOT__fs_in_y;
        SData/*9:0*/ gpu_top__DOT__pixel_x;
        SData/*9:0*/ gpu_top__DOT__pixel_y;
        SData/*11:0*/ gpu_top__DOT__decoder_inst__DOT__o_imm;
        SData/*15:0*/ gpu_top__DOT__vf_inst__DOT__i_vertex_index;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__i_v0_x;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__i_v0_y;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__i_v1_x;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__i_v1_y;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__i_v2_x;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__i_v2_y;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__o_fragment_x;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__o_fragment_y;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__v0_x_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__v0_y_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__v1_x_reg;
    };
    struct {
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__v1_y_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__v2_x_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__v2_y_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__x_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__y_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__bbox_min_x_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__bbox_min_y_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__bbox_max_x_reg;
        SData/*9:0*/ gpu_top__DOT__rast_inst__DOT__bbox_max_y_reg;
        SData/*9:0*/ gpu_top__DOT__fs_inst__DOT__i_frag_x;
        SData/*9:0*/ gpu_top__DOT__fs_inst__DOT__i_frag_y;
        SData/*9:0*/ gpu_top__DOT__fs_inst__DOT__o_pixel_x;
        SData/*9:0*/ gpu_top__DOT__fs_inst__DOT__o_pixel_y;
        SData/*15:0*/ gpu_top__DOT__tex_unit__DOT__i_u_coord;
        SData/*15:0*/ gpu_top__DOT__tex_unit__DOT__i_v_coord;
        SData/*15:0*/ gpu_top__DOT__tex_unit__DOT__tex_addr;
        SData/*9:0*/ gpu_top__DOT__fb_inst__DOT__i_pixel_x;
        SData/*9:0*/ gpu_top__DOT__fb_inst__DOT__i_pixel_y;
        VL_IN(i_bus_addr,31,0);
        VL_IN(i_bus_wdata,31,0);
        VL_OUT(o_bus_rdata,31,0);
        IData/*31:0*/ gpu_top__DOT__i_bus_addr;
        IData/*31:0*/ gpu_top__DOT__i_bus_wdata;
        IData/*31:0*/ gpu_top__DOT__o_bus_rdata;
        IData/*31:0*/ gpu_top__DOT__vertex_base_addr;
        IData/*31:0*/ gpu_top__DOT__shader_pc;
        VlWide<3>/*95:0*/ gpu_top__DOT__master_addr;
        VlWide<3>/*95:0*/ gpu_top__DOT__master_wdata;
        VlWide<3>/*95:0*/ gpu_top__DOT__master_rdata;
        IData/*31:0*/ gpu_top__DOT__slave_addr;
        IData/*31:0*/ gpu_top__DOT__slave_wdata;
        IData/*31:0*/ gpu_top__DOT__slave_rdata;
        IData/*31:0*/ gpu_top__DOT__shader_instruction;
        IData/*31:0*/ gpu_top__DOT__shader_host_rdata;
        VlWide<11>/*351:0*/ gpu_top__DOT__vertex_data;
        IData/*31:0*/ gpu_top__DOT__v0_color;
        IData/*31:0*/ gpu_top__DOT__v1_color;
        IData/*31:0*/ gpu_top__DOT__v2_color;
        IData/*31:0*/ gpu_top__DOT__v0_u;
        IData/*31:0*/ gpu_top__DOT__v0_v;
        IData/*31:0*/ gpu_top__DOT__v1_u;
        IData/*31:0*/ gpu_top__DOT__v1_v;
        IData/*31:0*/ gpu_top__DOT__v2_u;
        IData/*31:0*/ gpu_top__DOT__v2_v;
        IData/*20:0*/ gpu_top__DOT__lambda0;
        IData/*20:0*/ gpu_top__DOT__lambda1;
        IData/*20:0*/ gpu_top__DOT__lambda2;
        VlWide<3>/*82:0*/ gpu_top__DOT__fifo_wdata;
        VlWide<3>/*82:0*/ gpu_top__DOT__fifo_rdata;
        IData/*20:0*/ gpu_top__DOT__fs_in_lambda0;
        IData/*20:0*/ gpu_top__DOT__fs_in_lambda1;
        IData/*20:0*/ gpu_top__DOT__fs_in_lambda2;
        IData/*31:0*/ gpu_top__DOT__interpolated_color;
        IData/*31:0*/ gpu_top__DOT__interpolated_u;
        IData/*31:0*/ gpu_top__DOT__interpolated_v;
        IData/*31:0*/ gpu_top__DOT__tex_u;
        IData/*31:0*/ gpu_top__DOT__tex_v;
        IData/*31:0*/ gpu_top__DOT__texel_color_single;
        VlWide<4>/*127:0*/ gpu_top__DOT__texel_color_vec;
        VlWide<4>/*127:0*/ gpu_top__DOT__pixel_color;
        IData/*31:0*/ gpu_top__DOT__bram_rdata;
        IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__i_bus_addr;
        IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__i_bus_wdata;
        IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__o_bus_rdata;
    };
    struct {
        IData/*31:0*/ gpu_top__DOT__shader_loader_inst__DOT__i_host_wdata;
        IData/*31:0*/ gpu_top__DOT__shader_loader_inst__DOT__o_host_rdata;
        IData/*31:0*/ gpu_top__DOT__shader_loader_inst__DOT__o_gpu_instr;
        IData/*31:0*/ gpu_top__DOT__decoder_inst__DOT__i_instruction_word;
        VlWide<4>/*127:0*/ gpu_top__DOT__core0__DOT__rs1_data;
        VlWide<4>/*127:0*/ gpu_top__DOT__core0__DOT__rs2_data;
        VlWide<4>/*127:0*/ gpu_top__DOT__core0__DOT__alu_result;
        VlWide<4>/*127:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_wr_data;
        VlWide<4>/*127:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__o_rd_data_a;
        VlWide<4>/*127:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__o_rd_data_b;
        IData/*31:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__unnamedblk1__DOT__i;
        VlWide<4>/*127:0*/ gpu_top__DOT__core0__DOT__alu_inst__DOT__i_operand_a;
        VlWide<4>/*127:0*/ gpu_top__DOT__core0__DOT__alu_inst__DOT__i_operand_b;
        VlWide<4>/*127:0*/ gpu_top__DOT__core0__DOT__alu_inst__DOT__o_result;
        IData/*31:0*/ gpu_top__DOT__core0__DOT__alu_inst__DOT__unnamedblk1__DOT__i;
        VlWide<3>/*95:0*/ gpu_top__DOT__interconnect_inst__DOT__i_master_addr;
        VlWide<3>/*95:0*/ gpu_top__DOT__interconnect_inst__DOT__i_master_wdata;
        VlWide<3>/*95:0*/ gpu_top__DOT__interconnect_inst__DOT__o_master_rdata;
        IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__o_slave_addr;
        IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__o_slave_wdata;
        IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__i_slave_rdata;
        IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__granted_addr;
        IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__granted_wdata;
        IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT____Vlvbound_h3c2b5d2a__0;
        IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__unnamedblk1__DOT__unnamedblk2__DOT__i;
        IData/*31:0*/ gpu_top__DOT__vf_inst__DOT__i_base_addr;
        IData/*31:0*/ gpu_top__DOT__vf_inst__DOT__o_mem_addr;
        VlWide<11>/*351:0*/ gpu_top__DOT__vf_inst__DOT__i_mem_rdata;
        VlWide<11>/*351:0*/ gpu_top__DOT__vf_inst__DOT__o_vertex_data;
        VlWide<11>/*351:0*/ gpu_top__DOT__vf_inst__DOT__data_reg;
        IData/*20:0*/ gpu_top__DOT__rast_inst__DOT__o_lambda0;
        IData/*20:0*/ gpu_top__DOT__rast_inst__DOT__o_lambda1;
        IData/*20:0*/ gpu_top__DOT__rast_inst__DOT__o_lambda2;
        IData/*20:0*/ gpu_top__DOT__rast_inst__DOT__edge0;
        IData/*20:0*/ gpu_top__DOT__rast_inst__DOT__edge1;
        IData/*20:0*/ gpu_top__DOT__rast_inst__DOT__edge2;
        VlWide<3>/*82:0*/ gpu_top__DOT__frag_fifo__DOT__i_w_data;
        VlWide<3>/*82:0*/ gpu_top__DOT__frag_fifo__DOT__o_r_data;
        IData/*31:0*/ gpu_top__DOT__color_interp__DOT__i_attr0;
        IData/*31:0*/ gpu_top__DOT__color_interp__DOT__i_attr1;
        IData/*31:0*/ gpu_top__DOT__color_interp__DOT__i_attr2;
        IData/*20:0*/ gpu_top__DOT__color_interp__DOT__i_lambda0;
        IData/*20:0*/ gpu_top__DOT__color_interp__DOT__i_lambda1;
        IData/*20:0*/ gpu_top__DOT__color_interp__DOT__i_lambda2;
        IData/*31:0*/ gpu_top__DOT__color_interp__DOT__o_interpolated_attr;
        IData/*31:0*/ gpu_top__DOT__u_interp__DOT__i_attr0;
        IData/*31:0*/ gpu_top__DOT__u_interp__DOT__i_attr1;
        IData/*31:0*/ gpu_top__DOT__u_interp__DOT__i_attr2;
        IData/*20:0*/ gpu_top__DOT__u_interp__DOT__i_lambda0;
        IData/*20:0*/ gpu_top__DOT__u_interp__DOT__i_lambda1;
        IData/*20:0*/ gpu_top__DOT__u_interp__DOT__i_lambda2;
        IData/*31:0*/ gpu_top__DOT__u_interp__DOT__o_interpolated_attr;
        IData/*31:0*/ gpu_top__DOT__v_interp__DOT__i_attr0;
        IData/*31:0*/ gpu_top__DOT__v_interp__DOT__i_attr1;
        IData/*31:0*/ gpu_top__DOT__v_interp__DOT__i_attr2;
        IData/*20:0*/ gpu_top__DOT__v_interp__DOT__i_lambda0;
        IData/*20:0*/ gpu_top__DOT__v_interp__DOT__i_lambda1;
        IData/*20:0*/ gpu_top__DOT__v_interp__DOT__i_lambda2;
        IData/*31:0*/ gpu_top__DOT__v_interp__DOT__o_interpolated_attr;
        VlWide<4>/*127:0*/ gpu_top__DOT__fs_inst__DOT__i_frag_color;
        QData/*63:0*/ gpu_top__DOT__fs_inst__DOT__i_frag_tex_coord;
        IData/*31:0*/ gpu_top__DOT__fs_inst__DOT__o_tex_u_coord;
    };
    struct {
        IData/*31:0*/ gpu_top__DOT__fs_inst__DOT__o_tex_v_coord;
        VlWide<4>/*127:0*/ gpu_top__DOT__fs_inst__DOT__i_texel_color;
        VlWide<4>/*127:0*/ gpu_top__DOT__fs_inst__DOT__o_pixel_color;
        VlWide<4>/*127:0*/ gpu_top__DOT__fs_inst__DOT__modulated_color;
        VlWide<4>/*127:0*/ gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__i_operand_a;
        VlWide<4>/*127:0*/ gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__i_operand_b;
        VlWide<4>/*127:0*/ gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__o_result;
        IData/*31:0*/ gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ gpu_top__DOT__tex_unit__DOT__o_texel_color;
        IData/*31:0*/ gpu_top__DOT__fb_inst__DOT__i_pixel_color;
        IData/*18:0*/ gpu_top__DOT__fb_inst__DOT__o_mem_addr;
        IData/*31:0*/ gpu_top__DOT__fb_inst__DOT__o_mem_wdata;
        IData/*18:0*/ gpu_top__DOT__fb_inst__DOT__write_addr;
        IData/*31:0*/ __VactIterCount;
        QData/*52:0*/ gpu_top__DOT__color_interp__DOT__term0;
        QData/*52:0*/ gpu_top__DOT__color_interp__DOT__term1;
        QData/*52:0*/ gpu_top__DOT__color_interp__DOT__term2;
        QData/*54:0*/ gpu_top__DOT__color_interp__DOT__sum_terms;
        QData/*52:0*/ gpu_top__DOT__u_interp__DOT__term0;
        QData/*52:0*/ gpu_top__DOT__u_interp__DOT__term1;
        QData/*52:0*/ gpu_top__DOT__u_interp__DOT__term2;
        QData/*54:0*/ gpu_top__DOT__u_interp__DOT__sum_terms;
        QData/*52:0*/ gpu_top__DOT__v_interp__DOT__term0;
        QData/*52:0*/ gpu_top__DOT__v_interp__DOT__term1;
        QData/*52:0*/ gpu_top__DOT__v_interp__DOT__term2;
        QData/*54:0*/ gpu_top__DOT__v_interp__DOT__sum_terms;
        VlUnpacked<IData/*31:0*/, 262144> gpu_top__DOT__bram_memory;
        VlUnpacked<IData/*31:0*/, 256> gpu_top__DOT__shader_loader_inst__DOT__instruction_mem;
        VlUnpacked<VlWide<4>/*127:0*/, 16> gpu_top__DOT__core0__DOT__reg_file_inst__DOT__registers;
        VlUnpacked<VlWide<3>/*82:0*/, 64> gpu_top__DOT__frag_fifo__DOT__mem_array;
        VlUnpacked<IData/*31:0*/, 65536> gpu_top__DOT__tex_unit__DOT__texture_mem;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<23> __VactTriggered;
    VlTriggerVec<23> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr IData/*31:0*/ gpu_top__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__VEC_SIZE = 4U;
    static constexpr IData/*31:0*/ gpu_top__DOT__CORD_WIDTH = 0x0000000aU;
    static constexpr IData/*31:0*/ gpu_top__DOT__FB_WIDTH = 0x00000280U;
    static constexpr IData/*31:0*/ gpu_top__DOT__FB_HEIGHT = 0x000001e0U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__INSTR_DEPTH = 0x00000100U;
    static constexpr IData/*31:0*/ gpu_top__DOT__FIFO_DEPTH = 0x00000040U;
    static constexpr IData/*31:0*/ gpu_top__DOT__NUM_MASTERS = 3U;
    static constexpr IData/*31:0*/ gpu_top__DOT__NUM_SLAVES = 1U;
    static constexpr IData/*31:0*/ gpu_top__DOT__VERTEX_POS_BITS = 0x0000003cU;
    static constexpr IData/*31:0*/ gpu_top__DOT__VERTEX_COLOR_BITS = 0x00000060U;
    static constexpr IData/*31:0*/ gpu_top__DOT__VERTEX_UV_BITS = 0x000000c0U;
    static constexpr IData/*31:0*/ gpu_top__DOT__VERTEX_TOTAL_BITS_RAW = 0x0000015cU;
    static constexpr IData/*31:0*/ gpu_top__DOT__VERTEX_TOTAL_BITS = 0x00000160U;
    static constexpr IData/*31:0*/ gpu_top__DOT__FIFO_DATA_WIDTH = 0x00000053U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ADDR_CONTROL = 0U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ADDR_STATUS = 4U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ADDR_VERTEX_BASE = 8U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ADDR_VERTEX_COUNT = 0x0000000cU;
    static constexpr IData/*31:0*/ gpu_top__DOT__ADDR_PC = 0x00000010U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ADDR_SHADER_BASE = 0x00001000U;
    static constexpr IData/*31:0*/ gpu_top__DOT__INSTR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__BRAM_DEPTH = 0x00040000U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__QUEUE_DEPTH = 0x00000010U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__ADDR_CONTROL = 0U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__ADDR_STATUS = 4U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__CTRL_START_BIT = 0U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__CTRL_IRQ_CLEAR_BIT = 1U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__STATUS_BUSY_BIT = 0U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__STATUS_IRQ_PENDING_BIT = 1U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__STATUS_QUEUE_PENDING_BIT = 2U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__STATUS_QUEUE_COUNT_LOW = 4U;
    static constexpr IData/*31:0*/ gpu_top__DOT__ctrl_inst__DOT__STATUS_QUEUE_COUNT_HIGH = 7U;
    static constexpr IData/*31:0*/ gpu_top__DOT__shader_loader_inst__DOT__INSTR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__shader_loader_inst__DOT__INSTR_DEPTH = 0x00000100U;
    static constexpr IData/*31:0*/ gpu_top__DOT__core0__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__core0__DOT__VEC_SIZE = 4U;
    static constexpr IData/*31:0*/ gpu_top__DOT__core0__DOT__NUM_REGS = 0x00000010U;
    static constexpr IData/*31:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__DATA_WIDTH = 0x00000080U;
    static constexpr IData/*31:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__NUM_REGS = 0x00000010U;
    static constexpr IData/*31:0*/ gpu_top__DOT__core0__DOT__reg_file_inst__DOT__ADDR_WIDTH = 4U;
    static constexpr IData/*31:0*/ gpu_top__DOT__core0__DOT__alu_inst__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__core0__DOT__alu_inst__DOT__VECTOR_SIZE = 4U;
    static constexpr IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__NUM_MASTERS = 3U;
    static constexpr IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__NUM_SLAVES = 1U;
    static constexpr IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__NUM_REQUESTERS = 3U;
    static constexpr IData/*31:0*/ gpu_top__DOT__vf_inst__DOT__ATTR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__vf_inst__DOT__ATTRS_PER_VERTEX = 0x0000000bU;
    static constexpr IData/*31:0*/ gpu_top__DOT__vf_inst__DOT__ADDR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__vf_inst__DOT__VERTEXSTRIDE = 0x0000002cU;
    static constexpr IData/*31:0*/ gpu_top__DOT__rast_inst__DOT__CORD_WIDTH = 0x0000000aU;
    static constexpr IData/*31:0*/ gpu_top__DOT__frag_fifo__DOT__DATA_WIDTH = 0x00000053U;
    static constexpr IData/*31:0*/ gpu_top__DOT__frag_fifo__DOT__DEPTH = 0x00000040U;
    static constexpr IData/*31:0*/ gpu_top__DOT__frag_fifo__DOT__ADDR_WIDTH = 6U;
    static constexpr IData/*31:0*/ gpu_top__DOT__color_interp__DOT__ATTR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__color_interp__DOT__WEIGHT_WIDTH = 0x00000015U;
    static constexpr IData/*31:0*/ gpu_top__DOT__u_interp__DOT__ATTR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__u_interp__DOT__WEIGHT_WIDTH = 0x00000015U;
    static constexpr IData/*31:0*/ gpu_top__DOT__v_interp__DOT__ATTR_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__v_interp__DOT__WEIGHT_WIDTH = 0x00000015U;
    static constexpr IData/*31:0*/ gpu_top__DOT__fs_inst__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__fs_inst__DOT__VEC_SIZE = 4U;
    static constexpr IData/*31:0*/ gpu_top__DOT__fs_inst__DOT__CORD_WIDTH = 0x0000000aU;
    static constexpr IData/*31:0*/ gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__VECTOR_SIZE = 4U;
    static constexpr IData/*31:0*/ gpu_top__DOT__tex_unit__DOT__TEX_WIDTH = 0x00000100U;
    static constexpr IData/*31:0*/ gpu_top__DOT__tex_unit__DOT__TEX_HEIGHT = 0x00000100U;
    static constexpr IData/*31:0*/ gpu_top__DOT__tex_unit__DOT__CORD_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ gpu_top__DOT__tex_unit__DOT__DATA_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ gpu_top__DOT__tex_unit__DOT__TEX_DEPTH = 0x00010000U;
    static constexpr IData/*31:0*/ gpu_top__DOT__fb_inst__DOT__SCREEN_WIDTH = 0x00000280U;
    static constexpr IData/*31:0*/ gpu_top__DOT__fb_inst__DOT__SCREEN_HEIGHT = 0x000001e0U;
    static constexpr IData/*31:0*/ gpu_top__DOT__fb_inst__DOT__COLOR_WIDTH = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
