// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_gpu_top);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__color_interp);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__core0);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__ctrl_inst);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__decoder_inst);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__fb_inst);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__frag_fifo);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__fs_inst);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__interconnect_inst);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__rast_inst);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__reset_sync_inst);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__shader_loader_inst);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__tex_unit);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__u_interp);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__v_interp);
    __Vhier.remove(&__Vscope_gpu_top, &__Vscope_gpu_top__vf_inst);
    __Vhier.remove(&__Vscope_gpu_top__core0, &__Vscope_gpu_top__core0__alu_inst);
    __Vhier.remove(&__Vscope_gpu_top__core0, &__Vscope_gpu_top__core0__reg_file_inst);
    __Vhier.remove(&__Vscope_gpu_top__core0__alu_inst, &__Vscope_gpu_top__core0__alu_inst__unnamedblk1);
    __Vhier.remove(&__Vscope_gpu_top__core0__reg_file_inst, &__Vscope_gpu_top__core0__reg_file_inst__unnamedblk1);
    __Vhier.remove(&__Vscope_gpu_top__fs_inst, &__Vscope_gpu_top__fs_inst__alu_inst);
    __Vhier.remove(&__Vscope_gpu_top__fs_inst__alu_inst, &__Vscope_gpu_top__fs_inst__alu_inst__unnamedblk1);
    __Vhier.remove(&__Vscope_gpu_top__interconnect_inst, &__Vscope_gpu_top__interconnect_inst__arbiter_inst);
    __Vhier.remove(&__Vscope_gpu_top__interconnect_inst, &__Vscope_gpu_top__interconnect_inst__unnamedblk1);
    __Vhier.remove(&__Vscope_gpu_top__interconnect_inst, &__Vscope_gpu_top__interconnect_inst__unnamedblk2);
    __Vhier.remove(&__Vscope_gpu_top__interconnect_inst__arbiter_inst, &__Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1);
    __Vhier.remove(&__Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1, &__Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1__unnamedblk2);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(153);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_gpu_top.configure(this, name(), "gpu_top", "gpu_top", "gpu_top", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__color_interp.configure(this, name(), "gpu_top.color_interp", "color_interp", "attribute_interpolator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__core0.configure(this, name(), "gpu_top.core0", "core0", "shader_core", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__core0__alu_inst.configure(this, name(), "gpu_top.core0.alu_inst", "alu_inst", "alu", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__core0__alu_inst__unnamedblk1.configure(this, name(), "gpu_top.core0.alu_inst.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_gpu_top__core0__reg_file_inst.configure(this, name(), "gpu_top.core0.reg_file_inst", "reg_file_inst", "gpu_register_file", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__core0__reg_file_inst__unnamedblk1.configure(this, name(), "gpu_top.core0.reg_file_inst.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_gpu_top__ctrl_inst.configure(this, name(), "gpu_top.ctrl_inst", "ctrl_inst", "controller", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__decoder_inst.configure(this, name(), "gpu_top.decoder_inst", "decoder_inst", "instruction_decoder", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__fb_inst.configure(this, name(), "gpu_top.fb_inst", "fb_inst", "framebuffer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__frag_fifo.configure(this, name(), "gpu_top.frag_fifo", "frag_fifo", "fifo", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__fs_inst.configure(this, name(), "gpu_top.fs_inst", "fs_inst", "fragment_shader", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__fs_inst__alu_inst.configure(this, name(), "gpu_top.fs_inst.alu_inst", "alu_inst", "alu", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__fs_inst__alu_inst__unnamedblk1.configure(this, name(), "gpu_top.fs_inst.alu_inst.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_gpu_top__interconnect_inst.configure(this, name(), "gpu_top.interconnect_inst", "interconnect_inst", "_interconnect", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__interconnect_inst__arbiter_inst.configure(this, name(), "gpu_top.interconnect_inst.arbiter_inst", "arbiter_inst", "arbiter", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1.configure(this, name(), "gpu_top.interconnect_inst.arbiter_inst.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1__unnamedblk2.configure(this, name(), "gpu_top.interconnect_inst.arbiter_inst.unnamedblk1.unnamedblk2", "unnamedblk2", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_gpu_top__interconnect_inst__unnamedblk1.configure(this, name(), "gpu_top.interconnect_inst.unnamedblk1", "unnamedblk1", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_gpu_top__interconnect_inst__unnamedblk2.configure(this, name(), "gpu_top.interconnect_inst.unnamedblk2", "unnamedblk2", "<null>", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_gpu_top__rast_inst.configure(this, name(), "gpu_top.rast_inst", "rast_inst", "rasterizer", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__reset_sync_inst.configure(this, name(), "gpu_top.reset_sync_inst", "reset_sync_inst", "reset_sync", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__shader_loader_inst.configure(this, name(), "gpu_top.shader_loader_inst", "shader_loader_inst", "shader_loader", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__tex_unit.configure(this, name(), "gpu_top.tex_unit", "tex_unit", "texture_unit", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__u_interp.configure(this, name(), "gpu_top.u_interp", "u_interp", "attribute_interpolator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__v_interp.configure(this, name(), "gpu_top.v_interp", "v_interp", "attribute_interpolator", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_gpu_top__vf_inst.configure(this, name(), "gpu_top.vf_inst", "vf_inst", "vertex_fetch", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_gpu_top);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__color_interp);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__core0);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__ctrl_inst);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__decoder_inst);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__fb_inst);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__frag_fifo);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__fs_inst);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__interconnect_inst);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__rast_inst);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__reset_sync_inst);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__shader_loader_inst);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__tex_unit);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__u_interp);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__v_interp);
    __Vhier.add(&__Vscope_gpu_top, &__Vscope_gpu_top__vf_inst);
    __Vhier.add(&__Vscope_gpu_top__core0, &__Vscope_gpu_top__core0__alu_inst);
    __Vhier.add(&__Vscope_gpu_top__core0, &__Vscope_gpu_top__core0__reg_file_inst);
    __Vhier.add(&__Vscope_gpu_top__core0__alu_inst, &__Vscope_gpu_top__core0__alu_inst__unnamedblk1);
    __Vhier.add(&__Vscope_gpu_top__core0__reg_file_inst, &__Vscope_gpu_top__core0__reg_file_inst__unnamedblk1);
    __Vhier.add(&__Vscope_gpu_top__fs_inst, &__Vscope_gpu_top__fs_inst__alu_inst);
    __Vhier.add(&__Vscope_gpu_top__fs_inst__alu_inst, &__Vscope_gpu_top__fs_inst__alu_inst__unnamedblk1);
    __Vhier.add(&__Vscope_gpu_top__interconnect_inst, &__Vscope_gpu_top__interconnect_inst__arbiter_inst);
    __Vhier.add(&__Vscope_gpu_top__interconnect_inst, &__Vscope_gpu_top__interconnect_inst__unnamedblk1);
    __Vhier.add(&__Vscope_gpu_top__interconnect_inst, &__Vscope_gpu_top__interconnect_inst__unnamedblk2);
    __Vhier.add(&__Vscope_gpu_top__interconnect_inst__arbiter_inst, &__Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1);
    __Vhier.add(&__Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1, &__Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1__unnamedblk2);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"i_bus_addr", &(TOP.i_bus_addr), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"i_bus_wdata", &(TOP.i_bus_wdata), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"i_bus_we", &(TOP.i_bus_we), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"o_bus_rdata", &(TOP.o_bus_rdata), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst_n", &(TOP.rst_n), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"ADDR_CONTROL", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ADDR_CONTROL))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"ADDR_PC", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ADDR_PC))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"ADDR_SHADER_BASE", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ADDR_SHADER_BASE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"ADDR_STATUS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ADDR_STATUS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"ADDR_VERTEX_BASE", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ADDR_VERTEX_BASE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"ADDR_VERTEX_COUNT", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ADDR_VERTEX_COUNT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ADDR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"BRAM_DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__BRAM_DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"CORD_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__CORD_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"FB_HEIGHT", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__FB_HEIGHT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"FB_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__FB_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"FIFO_DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__FIFO_DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"FIFO_DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__FIFO_DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"INSTR_DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__INSTR_DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"INSTR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__INSTR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"NUM_MASTERS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__NUM_MASTERS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"NUM_SLAVES", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__NUM_SLAVES))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"VEC_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__VEC_SIZE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"VERTEX_COLOR_BITS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__VERTEX_COLOR_BITS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"VERTEX_POS_BITS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__VERTEX_POS_BITS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"VERTEX_TOTAL_BITS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__VERTEX_TOTAL_BITS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"VERTEX_TOTAL_BITS_RAW", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__VERTEX_TOTAL_BITS_RAW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"VERTEX_UV_BITS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__VERTEX_UV_BITS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"bram_memory", &(TOP.gpu_top__DOT__bram_memory), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,262143 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"bram_rdata", &(TOP.gpu_top__DOT__bram_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"controller_irq", &(TOP.gpu_top__DOT__controller_irq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"controller_start", &(TOP.gpu_top__DOT__controller_start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"current_vertex", &(TOP.gpu_top__DOT__current_vertex), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fifo_empty", &(TOP.gpu_top__DOT__fifo_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fifo_full", &(TOP.gpu_top__DOT__fifo_full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fifo_rd", &(TOP.gpu_top__DOT__fifo_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fifo_rdata", &(TOP.gpu_top__DOT__fifo_rdata), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,82,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fifo_wdata", &(TOP.gpu_top__DOT__fifo_wdata), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,82,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fifo_wr", &(TOP.gpu_top__DOT__fifo_wr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"frag_x", &(TOP.gpu_top__DOT__frag_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"frag_y", &(TOP.gpu_top__DOT__frag_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fs_in_lambda0", &(TOP.gpu_top__DOT__fs_in_lambda0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fs_in_lambda1", &(TOP.gpu_top__DOT__fs_in_lambda1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fs_in_lambda2", &(TOP.gpu_top__DOT__fs_in_lambda2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fs_in_valid", &(TOP.gpu_top__DOT__fs_in_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fs_in_x", &(TOP.gpu_top__DOT__fs_in_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"fs_in_y", &(TOP.gpu_top__DOT__fs_in_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"glbl_rst_n", &(TOP.gpu_top__DOT__glbl_rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"i_bus_addr", &(TOP.gpu_top__DOT__i_bus_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"i_bus_wdata", &(TOP.gpu_top__DOT__i_bus_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"i_bus_we", &(TOP.gpu_top__DOT__i_bus_we), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"interpolated_color", &(TOP.gpu_top__DOT__interpolated_color), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"interpolated_u", &(TOP.gpu_top__DOT__interpolated_u), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"interpolated_v", &(TOP.gpu_top__DOT__interpolated_v), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"lambda0", &(TOP.gpu_top__DOT__lambda0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"lambda1", &(TOP.gpu_top__DOT__lambda1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"lambda2", &(TOP.gpu_top__DOT__lambda2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"master_addr", &(TOP.gpu_top__DOT__master_addr), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,2,0 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"master_rdata", &(TOP.gpu_top__DOT__master_rdata), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,2,0 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"master_req", &(TOP.gpu_top__DOT__master_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"master_wdata", &(TOP.gpu_top__DOT__master_wdata), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,2,0 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"next_pipe_state", &(TOP.gpu_top__DOT__next_pipe_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"o_bus_rdata", &(TOP.gpu_top__DOT__o_bus_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"pipe_state", &(TOP.gpu_top__DOT__pipe_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"pipeline_busy", &(TOP.gpu_top__DOT__pipeline_busy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"pipeline_start", &(TOP.gpu_top__DOT__pipeline_start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"pixel_color", &(TOP.gpu_top__DOT__pixel_color), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"pixel_we", &(TOP.gpu_top__DOT__pixel_we), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"pixel_x", &(TOP.gpu_top__DOT__pixel_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"pixel_y", &(TOP.gpu_top__DOT__pixel_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"rast_frag_valid", &(TOP.gpu_top__DOT__rast_frag_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"rast_start", &(TOP.gpu_top__DOT__rast_start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"rasterizer_done", &(TOP.gpu_top__DOT__rasterizer_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_exec_done", &(TOP.gpu_top__DOT__shader_exec_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_exec_en", &(TOP.gpu_top__DOT__shader_exec_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_host_rdata", &(TOP.gpu_top__DOT__shader_host_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_imm", &(TOP.gpu_top__DOT__shader_imm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_instruction", &(TOP.gpu_top__DOT__shader_instruction), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_opcode", &(TOP.gpu_top__DOT__shader_opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_pc", &(TOP.gpu_top__DOT__shader_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_rd", &(TOP.gpu_top__DOT__shader_rd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_rs1", &(TOP.gpu_top__DOT__shader_rs1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"shader_rs2", &(TOP.gpu_top__DOT__shader_rs2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"slave_addr", &(TOP.gpu_top__DOT__slave_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,2 ,0,0 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"slave_rdata", &(TOP.gpu_top__DOT__slave_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,2 ,0,0 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"slave_req", &(TOP.gpu_top__DOT__slave_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"slave_wdata", &(TOP.gpu_top__DOT__slave_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,2 ,0,0 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"tex_req_valid", &(TOP.gpu_top__DOT__tex_req_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"tex_u", &(TOP.gpu_top__DOT__tex_u), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"tex_v", &(TOP.gpu_top__DOT__tex_v), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"texel_color_single", &(TOP.gpu_top__DOT__texel_color_single), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"texel_color_vec", &(TOP.gpu_top__DOT__texel_color_vec), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"texel_valid", &(TOP.gpu_top__DOT__texel_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v0_color", &(TOP.gpu_top__DOT__v0_color), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v0_u", &(TOP.gpu_top__DOT__v0_u), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v0_v", &(TOP.gpu_top__DOT__v0_v), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v0x", &(TOP.gpu_top__DOT__v0x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v0y", &(TOP.gpu_top__DOT__v0y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v1_color", &(TOP.gpu_top__DOT__v1_color), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v1_u", &(TOP.gpu_top__DOT__v1_u), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v1_v", &(TOP.gpu_top__DOT__v1_v), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v1x", &(TOP.gpu_top__DOT__v1x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v1y", &(TOP.gpu_top__DOT__v1y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v2_color", &(TOP.gpu_top__DOT__v2_color), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v2_u", &(TOP.gpu_top__DOT__v2_u), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v2_v", &(TOP.gpu_top__DOT__v2_v), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v2x", &(TOP.gpu_top__DOT__v2x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"v2y", &(TOP.gpu_top__DOT__v2y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"vertex_base_addr", &(TOP.gpu_top__DOT__vertex_base_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"vertex_count", &(TOP.gpu_top__DOT__vertex_count), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"vertex_data", &(TOP.gpu_top__DOT__vertex_data), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,351,0);
        __Vscope_gpu_top.varInsert(__Vfinal,"vertex_fetch_done", &(TOP.gpu_top__DOT__vertex_fetch_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"ATTR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__color_interp__DOT__ATTR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"WEIGHT_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__color_interp__DOT__WEIGHT_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"i_attr0", &(TOP.gpu_top__DOT__color_interp__DOT__i_attr0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"i_attr1", &(TOP.gpu_top__DOT__color_interp__DOT__i_attr1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"i_attr2", &(TOP.gpu_top__DOT__color_interp__DOT__i_attr2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"i_lambda0", &(TOP.gpu_top__DOT__color_interp__DOT__i_lambda0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"i_lambda1", &(TOP.gpu_top__DOT__color_interp__DOT__i_lambda1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"i_lambda2", &(TOP.gpu_top__DOT__color_interp__DOT__i_lambda2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"o_interpolated_attr", &(TOP.gpu_top__DOT__color_interp__DOT__o_interpolated_attr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"sum_terms", &(TOP.gpu_top__DOT__color_interp__DOT__sum_terms), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,54,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"term0", &(TOP.gpu_top__DOT__color_interp__DOT__term0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,52,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"term1", &(TOP.gpu_top__DOT__color_interp__DOT__term1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,52,0);
        __Vscope_gpu_top__color_interp.varInsert(__Vfinal,"term2", &(TOP.gpu_top__DOT__color_interp__DOT__term2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,52,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__core0__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"NUM_REGS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__core0__DOT__NUM_REGS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"VEC_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__core0__DOT__VEC_SIZE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"alu_result", &(TOP.gpu_top__DOT__core0__DOT__alu_result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__core0__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"i_exec_en", &(TOP.gpu_top__DOT__core0__DOT__i_exec_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"i_mem_ready", &(TOP.gpu_top__DOT__core0__DOT__i_mem_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"i_opcode", &(TOP.gpu_top__DOT__core0__DOT__i_opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"i_rd_addr", &(TOP.gpu_top__DOT__core0__DOT__i_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"i_rs1_addr", &(TOP.gpu_top__DOT__core0__DOT__i_rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"i_rs2_addr", &(TOP.gpu_top__DOT__core0__DOT__i_rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"o_mem_req", &(TOP.gpu_top__DOT__core0__DOT__o_mem_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"reg_write_en", &(TOP.gpu_top__DOT__core0__DOT__reg_write_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"rs1_data", &(TOP.gpu_top__DOT__core0__DOT__rs1_data), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"rs2_data", &(TOP.gpu_top__DOT__core0__DOT__rs2_data), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__core0.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__core0__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__core0__alu_inst.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__core0__DOT__alu_inst__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__core0__alu_inst.varInsert(__Vfinal,"VECTOR_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__core0__DOT__alu_inst__DOT__VECTOR_SIZE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__core0__alu_inst.varInsert(__Vfinal,"i_opcode", &(TOP.gpu_top__DOT__core0__DOT__alu_inst__DOT__i_opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_gpu_top__core0__alu_inst.varInsert(__Vfinal,"i_operand_a", &(TOP.gpu_top__DOT__core0__DOT__alu_inst__DOT__i_operand_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__core0__alu_inst.varInsert(__Vfinal,"i_operand_b", &(TOP.gpu_top__DOT__core0__DOT__alu_inst__DOT__i_operand_b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__core0__alu_inst.varInsert(__Vfinal,"o_result", &(TOP.gpu_top__DOT__core0__DOT__alu_inst__DOT__o_result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__core0__alu_inst__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.gpu_top__DOT__core0__DOT__alu_inst__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__ADDR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"NUM_REGS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__NUM_REGS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"i_rd_addr_a", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_rd_addr_a), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"i_rd_addr_b", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_rd_addr_b), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"i_wr_addr", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_wr_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"i_wr_data", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_wr_data), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"i_wr_en", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__i_wr_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"o_rd_data_a", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__o_rd_data_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"o_rd_data_b", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__o_rd_data_b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,127,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"registers", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__registers), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1,1 ,15,0 ,127,0);
        __Vscope_gpu_top__core0__reg_file_inst.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__core0__reg_file_inst__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.gpu_top__DOT__core0__DOT__reg_file_inst__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"ADDR_CONTROL", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__ADDR_CONTROL))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"ADDR_STATUS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__ADDR_STATUS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"CTRL_IRQ_CLEAR_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__CTRL_IRQ_CLEAR_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"CTRL_START_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__CTRL_START_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"QUEUE_DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__QUEUE_DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"STATUS_BUSY_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__STATUS_BUSY_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"STATUS_IRQ_PENDING_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__STATUS_IRQ_PENDING_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"STATUS_QUEUE_COUNT_HIGH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__STATUS_QUEUE_COUNT_HIGH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"STATUS_QUEUE_COUNT_LOW", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__STATUS_QUEUE_COUNT_LOW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"STATUS_QUEUE_PENDING_BIT", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__ctrl_inst__DOT__STATUS_QUEUE_PENDING_BIT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"busy_last_cycle", &(TOP.gpu_top__DOT__ctrl_inst__DOT__busy_last_cycle), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__ctrl_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"fire_start_pulse", &(TOP.gpu_top__DOT__ctrl_inst__DOT__fire_start_pulse), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"i_bus_addr", &(TOP.gpu_top__DOT__ctrl_inst__DOT__i_bus_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"i_bus_wdata", &(TOP.gpu_top__DOT__ctrl_inst__DOT__i_bus_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"i_bus_we", &(TOP.gpu_top__DOT__ctrl_inst__DOT__i_bus_we), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"i_pipeline_busy", &(TOP.gpu_top__DOT__ctrl_inst__DOT__i_pipeline_busy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"irq_clear_cmd", &(TOP.gpu_top__DOT__ctrl_inst__DOT__irq_clear_cmd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"irq_pending", &(TOP.gpu_top__DOT__ctrl_inst__DOT__irq_pending), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"o_bus_rdata", &(TOP.gpu_top__DOT__ctrl_inst__DOT__o_bus_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"o_irq", &(TOP.gpu_top__DOT__ctrl_inst__DOT__o_irq), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"o_start_pipeline", &(TOP.gpu_top__DOT__ctrl_inst__DOT__o_start_pipeline), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"pending_starts_count", &(TOP.gpu_top__DOT__ctrl_inst__DOT__pending_starts_count), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__ctrl_inst__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__ctrl_inst.varInsert(__Vfinal,"start_cmd", &(TOP.gpu_top__DOT__ctrl_inst__DOT__start_cmd), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__decoder_inst.varInsert(__Vfinal,"i_instruction_word", &(TOP.gpu_top__DOT__decoder_inst__DOT__i_instruction_word), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__decoder_inst.varInsert(__Vfinal,"o_imm", &(TOP.gpu_top__DOT__decoder_inst__DOT__o_imm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_gpu_top__decoder_inst.varInsert(__Vfinal,"o_opcode", &(TOP.gpu_top__DOT__decoder_inst__DOT__o_opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_gpu_top__decoder_inst.varInsert(__Vfinal,"o_rd_addr", &(TOP.gpu_top__DOT__decoder_inst__DOT__o_rd_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__decoder_inst.varInsert(__Vfinal,"o_rs1_addr", &(TOP.gpu_top__DOT__decoder_inst__DOT__o_rs1_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__decoder_inst.varInsert(__Vfinal,"o_rs2_addr", &(TOP.gpu_top__DOT__decoder_inst__DOT__o_rs2_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"COLOR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__fb_inst__DOT__COLOR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"SCREEN_HEIGHT", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__fb_inst__DOT__SCREEN_HEIGHT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"SCREEN_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__fb_inst__DOT__SCREEN_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__fb_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"i_pixel_color", &(TOP.gpu_top__DOT__fb_inst__DOT__i_pixel_color), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"i_pixel_we", &(TOP.gpu_top__DOT__fb_inst__DOT__i_pixel_we), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"i_pixel_x", &(TOP.gpu_top__DOT__fb_inst__DOT__i_pixel_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"i_pixel_y", &(TOP.gpu_top__DOT__fb_inst__DOT__i_pixel_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"o_mem_addr", &(TOP.gpu_top__DOT__fb_inst__DOT__o_mem_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,18,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"o_mem_req", &(TOP.gpu_top__DOT__fb_inst__DOT__o_mem_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"o_mem_wdata", &(TOP.gpu_top__DOT__fb_inst__DOT__o_mem_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__fb_inst__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fb_inst.varInsert(__Vfinal,"write_addr", &(TOP.gpu_top__DOT__fb_inst__DOT__write_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,18,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__frag_fifo__DOT__ADDR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__frag_fifo__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__frag_fifo__DOT__DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__frag_fifo__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"count_next", &(TOP.gpu_top__DOT__frag_fifo__DOT__count_next), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"count_reg", &(TOP.gpu_top__DOT__frag_fifo__DOT__count_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,6,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"i_rd_en", &(TOP.gpu_top__DOT__frag_fifo__DOT__i_rd_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"i_w_data", &(TOP.gpu_top__DOT__frag_fifo__DOT__i_w_data), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,82,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"i_wr_en", &(TOP.gpu_top__DOT__frag_fifo__DOT__i_wr_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"mem_array", &(TOP.gpu_top__DOT__frag_fifo__DOT__mem_array), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,63 ,82,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"o_empty", &(TOP.gpu_top__DOT__frag_fifo__DOT__o_empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"o_full", &(TOP.gpu_top__DOT__frag_fifo__DOT__o_full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"o_r_data", &(TOP.gpu_top__DOT__frag_fifo__DOT__o_r_data), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,82,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"rd_ptr_next", &(TOP.gpu_top__DOT__frag_fifo__DOT__rd_ptr_next), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,5,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"rd_ptr_reg", &(TOP.gpu_top__DOT__frag_fifo__DOT__rd_ptr_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,5,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__frag_fifo__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"wr_ptr_next", &(TOP.gpu_top__DOT__frag_fifo__DOT__wr_ptr_next), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,5,0);
        __Vscope_gpu_top__frag_fifo.varInsert(__Vfinal,"wr_ptr_reg", &(TOP.gpu_top__DOT__frag_fifo__DOT__wr_ptr_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,5,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"CORD_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__fs_inst__DOT__CORD_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__fs_inst__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"VEC_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__fs_inst__DOT__VEC_SIZE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__fs_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"i_frag_color", &(TOP.gpu_top__DOT__fs_inst__DOT__i_frag_color), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"i_frag_tex_coord", &(TOP.gpu_top__DOT__fs_inst__DOT__i_frag_tex_coord), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,2 ,1,0 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"i_frag_valid", &(TOP.gpu_top__DOT__fs_inst__DOT__i_frag_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"i_frag_x", &(TOP.gpu_top__DOT__fs_inst__DOT__i_frag_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"i_frag_y", &(TOP.gpu_top__DOT__fs_inst__DOT__i_frag_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"i_texel_color", &(TOP.gpu_top__DOT__fs_inst__DOT__i_texel_color), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"i_texel_valid", &(TOP.gpu_top__DOT__fs_inst__DOT__i_texel_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"modulated_color", &(TOP.gpu_top__DOT__fs_inst__DOT__modulated_color), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"o_pixel_color", &(TOP.gpu_top__DOT__fs_inst__DOT__o_pixel_color), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"o_pixel_valid", &(TOP.gpu_top__DOT__fs_inst__DOT__o_pixel_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"o_pixel_x", &(TOP.gpu_top__DOT__fs_inst__DOT__o_pixel_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"o_pixel_y", &(TOP.gpu_top__DOT__fs_inst__DOT__o_pixel_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"o_tex_req_valid", &(TOP.gpu_top__DOT__fs_inst__DOT__o_tex_req_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"o_tex_u_coord", &(TOP.gpu_top__DOT__fs_inst__DOT__o_tex_u_coord), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"o_tex_v_coord", &(TOP.gpu_top__DOT__fs_inst__DOT__o_tex_v_coord), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__fs_inst__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fs_inst.varInsert(__Vfinal,"tex_request_sent", &(TOP.gpu_top__DOT__fs_inst__DOT__tex_request_sent), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__fs_inst__alu_inst.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__fs_inst__alu_inst.varInsert(__Vfinal,"VECTOR_SIZE", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__VECTOR_SIZE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__fs_inst__alu_inst.varInsert(__Vfinal,"i_opcode", &(TOP.gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__i_opcode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_gpu_top__fs_inst__alu_inst.varInsert(__Vfinal,"i_operand_a", &(TOP.gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__i_operand_a), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__fs_inst__alu_inst.varInsert(__Vfinal,"i_operand_b", &(TOP.gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__i_operand_b), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__fs_inst__alu_inst.varInsert(__Vfinal,"o_result", &(TOP.gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__o_result), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,3,0 ,31,0);
        __Vscope_gpu_top__fs_inst__alu_inst__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.gpu_top__DOT__fs_inst__DOT__alu_inst__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__interconnect_inst__DOT__ADDR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__interconnect_inst__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"NUM_MASTERS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__interconnect_inst__DOT__NUM_MASTERS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"NUM_SLAVES", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__interconnect_inst__DOT__NUM_SLAVES))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__interconnect_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"granted_addr", &(TOP.gpu_top__DOT__interconnect_inst__DOT__granted_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"granted_index", &(TOP.gpu_top__DOT__interconnect_inst__DOT__granted_index), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"granted_wdata", &(TOP.gpu_top__DOT__interconnect_inst__DOT__granted_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"grants", &(TOP.gpu_top__DOT__interconnect_inst__DOT__grants), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"i_master_addr", &(TOP.gpu_top__DOT__interconnect_inst__DOT__i_master_addr), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,2,0 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"i_master_req", &(TOP.gpu_top__DOT__interconnect_inst__DOT__i_master_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"i_master_wdata", &(TOP.gpu_top__DOT__interconnect_inst__DOT__i_master_wdata), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,2,0 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"i_slave_rdata", &(TOP.gpu_top__DOT__interconnect_inst__DOT__i_slave_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,2 ,0,0 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"o_master_rdata", &(TOP.gpu_top__DOT__interconnect_inst__DOT__o_master_rdata), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,2 ,2,0 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"o_slave_addr", &(TOP.gpu_top__DOT__interconnect_inst__DOT__o_slave_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,2 ,0,0 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"o_slave_req", &(TOP.gpu_top__DOT__interconnect_inst__DOT__o_slave_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,0,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"o_slave_wdata", &(TOP.gpu_top__DOT__interconnect_inst__DOT__o_slave_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,2 ,0,0 ,31,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__interconnect_inst__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__interconnect_inst.varInsert(__Vfinal,"slave_select", &(TOP.gpu_top__DOT__interconnect_inst__DOT__slave_select), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst.varInsert(__Vfinal,"NUM_REQUESTERS", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__NUM_REQUESTERS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst.varInsert(__Vfinal,"i_requests", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__i_requests), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst.varInsert(__Vfinal,"last_grant_reg", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__last_grant_reg), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst.varInsert(__Vfinal,"masked_requests", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__masked_requests), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,5,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst.varInsert(__Vfinal,"next_grant_state", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__next_grant_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst.varInsert(__Vfinal,"o_grants", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__o_grants), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst.varInsert(__Vfinal,"priority_mask", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__priority_mask), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,5,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1.varInsert(__Vfinal,"grant_found", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__unnamedblk1__DOT__grant_found), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__interconnect_inst__arbiter_inst__unnamedblk1__unnamedblk2.varInsert(__Vfinal,"i", &(TOP.gpu_top__DOT__interconnect_inst__DOT__arbiter_inst__DOT__unnamedblk1__DOT__unnamedblk2__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst__unnamedblk1.varInsert(__Vfinal,"i", &(TOP.gpu_top__DOT__interconnect_inst__DOT__unnamedblk1__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__interconnect_inst__unnamedblk2.varInsert(__Vfinal,"i", &(TOP.gpu_top__DOT__interconnect_inst__DOT__unnamedblk2__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"CORD_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__rast_inst__DOT__CORD_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"bbox_max_x_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__bbox_max_x_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"bbox_max_y_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__bbox_max_y_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"bbox_min_x_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__bbox_min_x_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"bbox_min_y_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__bbox_min_y_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__rast_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"edge0", &(TOP.gpu_top__DOT__rast_inst__DOT__edge0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"edge1", &(TOP.gpu_top__DOT__rast_inst__DOT__edge1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"edge2", &(TOP.gpu_top__DOT__rast_inst__DOT__edge2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"i_start", &(TOP.gpu_top__DOT__rast_inst__DOT__i_start), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"i_v0_x", &(TOP.gpu_top__DOT__rast_inst__DOT__i_v0_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"i_v0_y", &(TOP.gpu_top__DOT__rast_inst__DOT__i_v0_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"i_v1_x", &(TOP.gpu_top__DOT__rast_inst__DOT__i_v1_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"i_v1_y", &(TOP.gpu_top__DOT__rast_inst__DOT__i_v1_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"i_v2_x", &(TOP.gpu_top__DOT__rast_inst__DOT__i_v2_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"i_v2_y", &(TOP.gpu_top__DOT__rast_inst__DOT__i_v2_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"is_inside", &(TOP.gpu_top__DOT__rast_inst__DOT__is_inside), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"is_running", &(TOP.gpu_top__DOT__rast_inst__DOT__is_running), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"o_done", &(TOP.gpu_top__DOT__rast_inst__DOT__o_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"o_fragment_valid", &(TOP.gpu_top__DOT__rast_inst__DOT__o_fragment_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"o_fragment_x", &(TOP.gpu_top__DOT__rast_inst__DOT__o_fragment_x), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"o_fragment_y", &(TOP.gpu_top__DOT__rast_inst__DOT__o_fragment_y), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"o_lambda0", &(TOP.gpu_top__DOT__rast_inst__DOT__o_lambda0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"o_lambda1", &(TOP.gpu_top__DOT__rast_inst__DOT__o_lambda1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"o_lambda2", &(TOP.gpu_top__DOT__rast_inst__DOT__o_lambda2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__rast_inst__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"v0_x_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__v0_x_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"v0_y_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__v0_y_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"v1_x_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__v1_x_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"v1_y_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__v1_y_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"v2_x_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__v2_x_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"v2_y_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__v2_y_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"x_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__x_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__rast_inst.varInsert(__Vfinal,"y_reg", &(TOP.gpu_top__DOT__rast_inst__DOT__y_reg), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,9,0);
        __Vscope_gpu_top__reset_sync_inst.varInsert(__Vfinal,"arst_n", &(TOP.gpu_top__DOT__reset_sync_inst__DOT__arst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__reset_sync_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__reset_sync_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__reset_sync_inst.varInsert(__Vfinal,"rst_s1", &(TOP.gpu_top__DOT__reset_sync_inst__DOT__rst_s1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__reset_sync_inst.varInsert(__Vfinal,"rst_s2", &(TOP.gpu_top__DOT__reset_sync_inst__DOT__rst_s2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__reset_sync_inst.varInsert(__Vfinal,"srst_n", &(TOP.gpu_top__DOT__reset_sync_inst__DOT__srst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"INSTR_DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__shader_loader_inst__DOT__INSTR_DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"INSTR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__shader_loader_inst__DOT__INSTR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__shader_loader_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"i_gpu_addr", &(TOP.gpu_top__DOT__shader_loader_inst__DOT__i_gpu_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"i_host_addr", &(TOP.gpu_top__DOT__shader_loader_inst__DOT__i_host_addr), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"i_host_wdata", &(TOP.gpu_top__DOT__shader_loader_inst__DOT__i_host_wdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"i_host_we", &(TOP.gpu_top__DOT__shader_loader_inst__DOT__i_host_we), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"instruction_mem", &(TOP.gpu_top__DOT__shader_loader_inst__DOT__instruction_mem), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,255,0 ,31,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"o_gpu_instr", &(TOP.gpu_top__DOT__shader_loader_inst__DOT__o_gpu_instr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"o_host_rdata", &(TOP.gpu_top__DOT__shader_loader_inst__DOT__o_host_rdata), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__shader_loader_inst.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__shader_loader_inst__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"CORD_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__tex_unit__DOT__CORD_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__tex_unit__DOT__DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"TEX_DEPTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__tex_unit__DOT__TEX_DEPTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"TEX_HEIGHT", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__tex_unit__DOT__TEX_HEIGHT))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"TEX_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__tex_unit__DOT__TEX_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__tex_unit__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"i_req_valid", &(TOP.gpu_top__DOT__tex_unit__DOT__i_req_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"i_u_coord", &(TOP.gpu_top__DOT__tex_unit__DOT__i_u_coord), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"i_v_coord", &(TOP.gpu_top__DOT__tex_unit__DOT__i_v_coord), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"o_data_valid", &(TOP.gpu_top__DOT__tex_unit__DOT__o_data_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"o_texel_color", &(TOP.gpu_top__DOT__tex_unit__DOT__o_texel_color), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__tex_unit__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"tex_addr", &(TOP.gpu_top__DOT__tex_unit__DOT__tex_addr), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"tex_x", &(TOP.gpu_top__DOT__tex_unit__DOT__tex_x), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"tex_y", &(TOP.gpu_top__DOT__tex_unit__DOT__tex_y), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_gpu_top__tex_unit.varInsert(__Vfinal,"texture_mem", &(TOP.gpu_top__DOT__tex_unit__DOT__texture_mem), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1,1 ,65535,0 ,31,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"ATTR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__u_interp__DOT__ATTR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"WEIGHT_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__u_interp__DOT__WEIGHT_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"i_attr0", &(TOP.gpu_top__DOT__u_interp__DOT__i_attr0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"i_attr1", &(TOP.gpu_top__DOT__u_interp__DOT__i_attr1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"i_attr2", &(TOP.gpu_top__DOT__u_interp__DOT__i_attr2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"i_lambda0", &(TOP.gpu_top__DOT__u_interp__DOT__i_lambda0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"i_lambda1", &(TOP.gpu_top__DOT__u_interp__DOT__i_lambda1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"i_lambda2", &(TOP.gpu_top__DOT__u_interp__DOT__i_lambda2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"o_interpolated_attr", &(TOP.gpu_top__DOT__u_interp__DOT__o_interpolated_attr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"sum_terms", &(TOP.gpu_top__DOT__u_interp__DOT__sum_terms), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,54,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"term0", &(TOP.gpu_top__DOT__u_interp__DOT__term0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,52,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"term1", &(TOP.gpu_top__DOT__u_interp__DOT__term1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,52,0);
        __Vscope_gpu_top__u_interp.varInsert(__Vfinal,"term2", &(TOP.gpu_top__DOT__u_interp__DOT__term2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,52,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"ATTR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__v_interp__DOT__ATTR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"WEIGHT_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__v_interp__DOT__WEIGHT_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"i_attr0", &(TOP.gpu_top__DOT__v_interp__DOT__i_attr0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"i_attr1", &(TOP.gpu_top__DOT__v_interp__DOT__i_attr1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"i_attr2", &(TOP.gpu_top__DOT__v_interp__DOT__i_attr2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"i_lambda0", &(TOP.gpu_top__DOT__v_interp__DOT__i_lambda0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"i_lambda1", &(TOP.gpu_top__DOT__v_interp__DOT__i_lambda1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"i_lambda2", &(TOP.gpu_top__DOT__v_interp__DOT__i_lambda2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,20,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"o_interpolated_attr", &(TOP.gpu_top__DOT__v_interp__DOT__o_interpolated_attr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"sum_terms", &(TOP.gpu_top__DOT__v_interp__DOT__sum_terms), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,54,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"term0", &(TOP.gpu_top__DOT__v_interp__DOT__term0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,52,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"term1", &(TOP.gpu_top__DOT__v_interp__DOT__term1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,52,0);
        __Vscope_gpu_top__v_interp.varInsert(__Vfinal,"term2", &(TOP.gpu_top__DOT__v_interp__DOT__term2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,52,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"ADDR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__vf_inst__DOT__ADDR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"ATTRS_PER_VERTEX", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__vf_inst__DOT__ATTRS_PER_VERTEX))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"ATTR_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__vf_inst__DOT__ATTR_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"VERTEXSTRIDE", const_cast<void*>(static_cast<const void*>(&(TOP.gpu_top__DOT__vf_inst__DOT__VERTEXSTRIDE))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"clk", &(TOP.gpu_top__DOT__vf_inst__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"current_state", &(TOP.gpu_top__DOT__vf_inst__DOT__current_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"data_reg", &(TOP.gpu_top__DOT__vf_inst__DOT__data_reg), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,351,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"i_base_addr", &(TOP.gpu_top__DOT__vf_inst__DOT__i_base_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"i_mem_rdata", &(TOP.gpu_top__DOT__vf_inst__DOT__i_mem_rdata), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,351,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"i_mem_ready", &(TOP.gpu_top__DOT__vf_inst__DOT__i_mem_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"i_start_fetch", &(TOP.gpu_top__DOT__vf_inst__DOT__i_start_fetch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"i_vertex_index", &(TOP.gpu_top__DOT__vf_inst__DOT__i_vertex_index), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"next_state", &(TOP.gpu_top__DOT__vf_inst__DOT__next_state), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"o_fetch_done", &(TOP.gpu_top__DOT__vf_inst__DOT__o_fetch_done), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"o_mem_addr", &(TOP.gpu_top__DOT__vf_inst__DOT__o_mem_addr), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"o_mem_req", &(TOP.gpu_top__DOT__vf_inst__DOT__o_mem_req), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"o_vertex_data", &(TOP.gpu_top__DOT__vf_inst__DOT__o_vertex_data), false, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,351,0);
        __Vscope_gpu_top__vf_inst.varInsert(__Vfinal,"rst_n", &(TOP.gpu_top__DOT__vf_inst__DOT__rst_n), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
    }
}
